### ISSUE TITLE
What's the difference between prox_nuclear and singular value shrinkage operator?

### ISSUE THREAD

**Issue by liulin1995** [canyilu/LibADMM-toolbox#1]
The paper "A Singular Value Thresholding Algorithm for Matrix Completion"  says that the singular value shrinkage operator is the solution to the problem :
 ` min_X lambda*||X||_*+0.5*||X-B||_F^2.`
I found that the prox_nuclear is also the solution to the above problem, but in code of prox_nuclear:
```
[U,S,V] = svd(B,'econ');
S = diag(S);
svp = length(find(S>lambda));
if svp>=1
    S = S(1:svp)-lambda;
    X = U(:,1:svp)*diag(S)*V(:,1:svp)';
    nuclearnorm = sum(S);
else
    X = zeros(size(B));
    nuclearnorm = 0;
end
```
~~only the singular values greater than lambda subtract the lambda, those singular value less than lambda but also greater than zero remain unchanged. It's different from SVT operator,so why not set those singular values less than lambda to zero? Any paper can help me understand it?~~

**Comment by canyilu** [comment]
The proximal operator of nuclear norm (prox_nuclear) is exactly the same as
the singular value shrinkage operator.

Best regards,

Canyi Lu

https://canyilu.github.io/

Carnegie Mellon University

**Comment by liulin1995** [comment]
Sorry, I misunderstood you code, you are right. Thank you for your response!
